from nn.disc.gail import GAIL
from nn.disc.dac import DAC
from nn.disc.airl import AIRL
from nn.disc.fairl import FAIRL
from nn.disc.reg_gau import RAIRLGaussian
from nn.disc.reg_dgau import RAIRLDiagGaussian
from nn.disc.md_gau import MirrorDescentGaussian
from nn.disc.md_dgau import MirrorDescentDiagGaussian
from nn.disc.reg_dgau2 import RAIRLDiagGaussian2
from nn.disc.md_dgau2 import MirrorDescentDiagGaussian2